/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.24).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.oconsent.api;

import io.oconsent.model.Body1;
import io.oconsent.model.Error;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-01-30T08:49:14.744Z[GMT]")
public interface UploadApi {

    @Operation(summary = "", description = "Retrieve the total number of uploaded files", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Upload - File" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "response", content = @Content(schema = @Schema(implementation = Body1.class))),
        
        @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "Not found", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/upload/files/count",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Body1> uploadFilesCountGet();


    @Operation(summary = "", description = "Retrieve all file documents", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Upload - File" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "response", content = @Content(schema = @Schema(implementation = Body1.class))),
        
        @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "Not found", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/upload/files",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Body1> uploadFilesGet();


    @Operation(summary = "", description = "Delete an uploaded file", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Upload - File" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "response", content = @Content(schema = @Schema(implementation = Body1.class))),
        
        @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "Not found", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/upload/files/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Body1> uploadFilesIdDelete(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") String id);


    @Operation(summary = "", description = "Retrieve a single file depending on its id", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Upload - File" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "response", content = @Content(schema = @Schema(implementation = Body1.class))),
        
        @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "Not found", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/upload/files/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Body1> uploadFilesIdGet(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") String id);


    @Operation(summary = "", description = "Upload a file", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Upload - File" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "response", content = @Content(schema = @Schema(implementation = Body1.class))),
        
        @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "Not found", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/upload/",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Body1> uploadPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Body1 body);


    @Operation(summary = "", description = "Search for an uploaded file", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Upload - File" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "response", content = @Content(schema = @Schema(implementation = Body1.class))),
        
        @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "404", description = "Not found", content = @Content(schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/upload/search/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Body1> uploadSearchIdGet(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") String id);

}

